name: StatisticsWebserver
version: '${project.version}'
main: de.flashyboi.minecraft.plugins.statisticswebserver.StatisticsWebserver
api-version: 1.17
authors: [ flash_btw ]
website: https://flash-codes.de
depend: [ SuperVanish, SuperiorSkyblock2 ]
